# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4478a264b593e40c0024e9ef173c95670c50945b1574c3f26bc094cfa4c20dbf62bfed95f5d851f9118c8a6f9627504c46b33758ed792dfe429d134f95c4975d

test:
  secret_key_base: cc0e86b476048bdbe22a581a22fffc0e30da4495bf9b9e0843142ff3fcf6a2d1ffcd4a80d6891f9f647da64c0be82ebdc6c89eb84019fd54e4d9c5cb4c317a72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
